name: Nostalgianavi
description: "Tour Attraction Recommendation app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  flutter_riverpod: ^2.4.9
  path_provider: ^2.0.2
  permission_handler: ^11.3.1

  google_sign_in: ^6.2.1

  image_picker: ^1.0.5
  intl: ^0.19.0
  dots_indicator: ^3.0.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  flutter_image_compress: ^2.1.0

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  camera: ^0.10.5+7
  photo_manager: ^3.0.0

  google_maps_flutter : ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Foxlite Script
      fonts:
        - asset: fonts/Foxlite Script.ttf
    - family: Apalu
      fonts:
        - asset: fonts/Apalu.ttf
    - family: Rembank
      fonts:
        - asset: fonts/Rembank.otf
    - family: Nephilm
      fonts:
        - asset: fonts/Nephilm.otf
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf
    - family: GmarketSansTTFBold
      fonts:
        - asset: fonts/GmarketSansTTFBold.ttf
    - family: GmarketSansTTFLight
      fonts:
        - asset: fonts/GmarketSansTTFLight.ttf
    - family: GmarketSansTTFMedium
      fonts:
        - asset: fonts/GmarketSansTTFMedium.ttf